name: Translation Feedback
description: Report translation issues
labels:
  - "📜 Translation | Translation Issue"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Slimefun issue reporting system!

        Before submitting feedback, please make sure:
        - You have checked whether the [latest version](https://github.com/Slimefun-United/Slimefun-United/releases) has already fixed the issue you encountered
        - You have searched existing [issues](https://github.com/Slimefun-United/Slimefun-United/issues) to see if a similar problem has been reported

        If your feedback is unclear or does not follow the template, it will be closed immediately.

  - type: textarea
    id: language
    attributes:
      label: Language in which the issue is present
      description: Just type the name of the language in English
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Description of the Translation Issue
      description: Describe the issue you encountered in detail
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Location of the Translation Error/Missing Text
      description: Briefly describe where the translation error or missing text appears
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun Version
      description: |
        **Do NOT write "latest version", or your feedback will be closed immediately**
        Please screenshot or copy the output of the command "/sf versions".
      placeholder: Slimefun United 4.10
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any extra information here if necessary
